// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerInfo {
    #[prost(string, tag = "1")]
    pub pluto_version: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "2")]
    pub lock_hash: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "3")]
    pub sent_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "4")]
    pub git_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag = "6")]
    pub builder_api_enabled: bool,
    #[prost(string, tag = "7")]
    pub nickname: ::prost::alloc::string::String,
}