// This file is @generated by prost-build.
/// Cluster represents the manifest of a cluster after applying a sequence of mutations.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cluster {
    /// InitialMutationHash is the hash of first signed mutation, uniquely identifying cluster, aka "cluster hash". It must be 32 bytes.
    #[prost(bytes = "bytes", tag = "1")]
    pub initial_mutation_hash: ::prost::bytes::Bytes,
    /// LatestMutationHash is the hash of last signed mutation, identifying this specific cluster iteration. It must be 32 bytes.
    #[prost(bytes = "bytes", tag = "2")]
    pub latest_mutation_hash: ::prost::bytes::Bytes,
    /// Name is the name of the cluster.
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// Threshold is the threshold of the cluster.
    #[prost(int32, tag = "4")]
    pub threshold: i32,
    /// DKGAlgorithm is the DKG algorithm used to create the validator keys of the cluster.
    #[prost(string, tag = "5")]
    pub dkg_algorithm: ::prost::alloc::string::String,
    /// ForkVersion is the fork version (network/chain) of the cluster. It must be 4 bytes.
    #[prost(bytes = "bytes", tag = "6")]
    pub fork_version: ::prost::bytes::Bytes,
    /// Operators is the list of operators of the cluster.
    #[prost(message, repeated, tag = "7")]
    pub operators: ::prost::alloc::vec::Vec<Operator>,
    /// Validators is the list of validators of the cluster.
    #[prost(message, repeated, tag = "8")]
    pub validators: ::prost::alloc::vec::Vec<Validator>,
    /// ConsensusProtocol is the consensus protocol name preferred by the cluster, e.g. "abft".
    #[prost(string, tag = "9")]
    pub consensus_protocol: ::prost::alloc::string::String,
    /// TargetGasLimit is the custom target gas limit for transactions.
    #[prost(uint32, tag = "10")]
    pub target_gas_limit: u32,
    /// Compounding is the flag to enable compounding rewards.
    #[prost(bool, tag = "11")]
    pub compounding: bool,
}
/// Mutation mutates the cluster manifest.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mutation {
    /// Parent is the hash of the parent mutation. It must be 32 bytes.
    #[prost(bytes = "bytes", tag = "1")]
    pub parent: ::prost::bytes::Bytes,
    /// Type is the type of mutation.
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    /// Data is the data of the mutation. Must be non-nil.
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<::prost_types::Any>,
}
/// SignedMutation is a mutation signed by a signer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedMutation {
    /// Mutation is the mutation.
    #[prost(message, optional, tag = "1")]
    pub mutation: ::core::option::Option<Mutation>,
    /// Signer is the identity (public key) of the signer.
    #[prost(bytes = "bytes", tag = "2")]
    pub signer: ::prost::bytes::Bytes,
    /// Signature is the signature of the mutation.
    #[prost(bytes = "bytes", tag = "3")]
    pub signature: ::prost::bytes::Bytes,
}
/// SignedMutationList is a list of signed mutations.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignedMutationList {
    /// Mutations is the list of mutations.
    #[prost(message, repeated, tag = "1")]
    pub mutations: ::prost::alloc::vec::Vec<SignedMutation>,
}
/// Operator represents the operator of a node in the cluster.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Operator {
    /// Address is the operator's Ethereum address.
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// enr identifies the operator's charon node.
    #[prost(string, tag = "2")]
    pub enr: ::prost::alloc::string::String,
}
/// Validator represents a distributed validator managed by the DV cluster.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Validator {
    /// PublicKey is the group public key of the validator.
    #[prost(bytes = "bytes", tag = "1")]
    pub public_key: ::prost::bytes::Bytes,
    /// PubShares is the ordered list of public shares of the validator.
    #[prost(bytes = "bytes", repeated, tag = "2")]
    pub pub_shares: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    /// FeeRecipientAddress is the fee recipient Ethereum address of the validator.
    #[prost(string, tag = "3")]
    pub fee_recipient_address: ::prost::alloc::string::String,
    /// WithdrawalAddress is the withdrawal Ethereum address of the validator.
    #[prost(string, tag = "4")]
    pub withdrawal_address: ::prost::alloc::string::String,
    /// BuilderRegistration is the pre-generated json-formatted builder-API validator registration of the validator.
    #[prost(bytes = "bytes", tag = "5")]
    pub builder_registration_json: ::prost::bytes::Bytes,
}
/// ValidatorList is a list of validators.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorList {
    /// Validators is the list of validators.
    #[prost(message, repeated, tag = "1")]
    pub validators: ::prost::alloc::vec::Vec<Validator>,
}
/// LegacyLock represents a json formatted legacy cluster lock file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LegacyLock {
    #[prost(bytes = "bytes", tag = "1")]
    pub json: ::prost::bytes::Bytes,
}
/// Empty is an empty/noop message.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
