// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParSigExMsg {
    #[prost(message, optional, tag = "1")]
    pub duty: ::core::option::Option<super::core::Duty>,
    #[prost(message, optional, tag = "2")]
    pub data_set: ::core::option::Option<super::core::ParSignedDataSet>,
}