// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QbftMsg {
    #[prost(int64, tag = "1")]
    pub r#type: i64,
    #[prost(message, optional, tag = "2")]
    pub duty: ::core::option::Option<super::core::Duty>,
    #[prost(int64, tag = "3")]
    pub peer_idx: i64,
    #[prost(int64, tag = "4")]
    pub round: i64,
    #[prost(int64, tag = "6")]
    pub prepared_round: i64,
    #[prost(bytes = "bytes", tag = "8")]
    pub signature: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "11")]
    pub value_hash: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "12")]
    pub prepared_value_hash: ::prost::bytes::Bytes,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QbftConsensusMsg {
    /// msg is the message that we send
    #[prost(message, optional, tag = "1")]
    pub msg: ::core::option::Option<QbftMsg>,
    /// justification is the justifications from others for the message
    #[prost(message, repeated, tag = "2")]
    pub justification: ::prost::alloc::vec::Vec<QbftMsg>,
    /// values of the hashes in the messages
    #[prost(message, repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffedConsensusMsg {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Other consensus protocol messages can be added here
    #[prost(message, optional, tag = "2")]
    pub msg: ::core::option::Option<QbftConsensusMsg>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffedConsensusInstance {
    #[prost(message, optional, tag = "1")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag = "2")]
    pub nodes: i64,
    #[prost(int64, tag = "3")]
    pub peer_idx: i64,
    #[prost(message, repeated, tag = "4")]
    pub msgs: ::prost::alloc::vec::Vec<SniffedConsensusMsg>,
    #[prost(string, tag = "5")]
    pub protocol_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffedConsensusInstances {
    #[prost(message, repeated, tag = "1")]
    pub instances: ::prost::alloc::vec::Vec<SniffedConsensusInstance>,
    #[prost(string, tag = "2")]
    pub git_hash: ::prost::alloc::string::String,
}
