// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

/// core.Duty
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Duty {
    /// uint64
    #[prost(uint64, tag = "1")]
    pub slot: u64,
    /// core.DutyType
    #[prost(int32, tag = "2")]
    pub r#type: i32,
}
/// core.UnsignedDataSet
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnsignedDataSet {
    /// map\[core.PubKey\]core.UnsignedData
    #[prost(btree_map = "string, bytes", tag = "1")]
    pub set: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::bytes::Bytes,
    >,
}
/// core.ParSignedDataSet
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParSignedDataSet {
    /// map\[core.PubKey\]core.ParSignedData
    #[prost(btree_map = "string, message", tag = "1")]
    pub set: ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, ParSignedData>,
}
/// core.ParSignedData
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParSignedData {
    /// \[\]byte
    #[prost(bytes = "bytes", tag = "1")]
    pub data: ::prost::bytes::Bytes,
    /// core.Signature
    #[prost(bytes = "bytes", tag = "2")]
    pub signature: ::prost::bytes::Bytes,
    /// int
    #[prost(int32, tag = "3")]
    pub share_idx: i32,
}
