// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

/// PriorityResult defines a cluster wide priority result of the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityResult {
    #[prost(message, repeated, tag = "1")]
    pub msgs: ::prost::alloc::vec::Vec<PriorityMsg>,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<PriorityTopicResult>,
}
/// PriorityMsg defines all the priorities and metadata of a single peer in the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityMsg {
    #[prost(message, optional, tag = "1")]
    pub duty: ::core::option::Option<super::core::Duty>,
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<PriorityTopicProposal>,
    #[prost(string, tag = "3")]
    pub peer_id: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "4")]
    pub signature: ::prost::bytes::Bytes,
}
/// PriorityTopicProposal defines a single peers proposed priorities for a single topic in the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityTopicProposal {
    #[prost(message, optional, tag = "1")]
    pub topic: ::core::option::Option<::prost_types::Any>,
    #[prost(message, repeated, tag = "2")]
    pub priorities: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
/// PriorityTopicResult defines the cluster wide resulting priorities for a
/// single topic in the Prioritiser protocol.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriorityTopicResult {
    #[prost(message, optional, tag = "1")]
    pub topic: ::core::option::Option<::prost_types::Any>,
    /// priorities are ordered by decreasing score, ties are broken by peer with lowest peer ID.
    #[prost(message, repeated, tag = "2")]
    pub priorities: ::prost::alloc::vec::Vec<PriorityScoredResult>,
}
/// PriorityScoredResult defines the cluster wide priority score in the Prioritiser protocol.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PriorityScoredResult {
    #[prost(message, optional, tag = "1")]
    pub priority: ::core::option::Option<::prost_types::Any>,
    #[prost(int64, tag = "2")]
    pub score: i64,
}