use libp2p::PeerId;

/// List of 144 nouns for peer name generation.
const NOUNS: &[&str] = &[
    "adult",
    "age",
    "amount",
    "area",
    "back",
    "bed",
    "blood",
    "body",
    "book",
    "box",
    "boy",
    "bulb",
    "bunch",
    "business",
    "camera",
    "chicken",
    "child",
    "chocolates",
    "city",
    "clothes",
    "colony",
    "colors",
    "company",
    "computer",
    "continent",
    "council",
    "country",
    "course",
    "cycle",
    "dates",
    "day",
    "death",
    "desk",
    "door",
    "egg",
    "face",
    "fact",
    "factory",
    "family",
    "farm",
    "farmer",
    "father",
    "fish",
    "floor",
    "flowers",
    "food",
    "fridge",
    "future",
    "game",
    "garden",
    "gas",
    "glass",
    "group",
    "health",
    "hill",
    "hospital",
    "idea",
    "image",
    "industry",
    "island",
    "jewelry",
    "job",
    "kitchen",
    "land",
    "law",
    "leaves",
    "leg",
    "letter",
    "life",
    "magazine",
    "market",
    "metal",
    "mirror",
    "mobile",
    "money",
    "morning",
    "mother",
    "mountain",
    "movie",
    "name",
    "nest",
    "news",
    "ocean",
    "oil",
    "painter",
    "park",
    "party",
    "pen",
    "pen",
    "pencil",
    "person",
    "picture",
    "pillow",
    "place",
    "plant",
    "pond",
    "rain",
    "rate",
    "result",
    "ring",
    "road",
    "rock",
    "rocket",
    "room",
    "rope",
    "rule",
    "sale",
    "school",
    "shape",
    "shapes",
    "ship",
    "shop",
    "sister",
    "site",
    "skin",
    "snacks",
    "son",
    "song",
    "sort",
    "sound",
    "soup",
    "sports",
    "state",
    "stone",
    "street",
    "system",
    "taxi",
    "tea",
    "teacher",
    "team",
    "toy",
    "tractor",
    "trade",
    "train",
    "video",
    "view",
    "water",
    "waterfall",
    "week",
    "women",
    "wood",
    "word",
    "year",
    "yesterday",
];

/// List of 196 adjectives for peer name generation.
const ADJECTIVES: &[&str] = &[
    "adorable",
    "adventurous",
    "affectionate",
    "aggressive",
    "agreeable",
    "alert",
    "alive",
    "amazing",
    "amiable",
    "ample",
    "amused",
    "angry",
    "annoyed",
    "anxious",
    "ashamed",
    "attractive",
    "average",
    "beautiful",
    "better",
    "bewildered",
    "black",
    "blushing",
    "bored",
    "bountiful",
    "brainy",
    "brave",
    "bright",
    "busy",
    "calm",
    "captivating",
    "careful",
    "cautious",
    "charming",
    "cheerful",
    "clear",
    "clever",
    "cloudy",
    "colorful",
    "combative",
    "comfortable",
    "confused",
    "considerate",
    "cooperative",
    "courageous",
    "crazy",
    "crowded",
    "cruel",
    "curious",
    "cute",
    "dangerous",
    "dark",
    "defiant",
    "dazzling",
    "delightful",
    "determined",
    "different",
    "distinct",
    "eager",
    "easy",
    "elated",
    "elegant",
    "embarrassed",
    "enchanting",
    "encouraging",
    "energetic",
    "engaging",
    "engrossing",
    "enthusiastic",
    "excited",
    "expensive",
    "exuberant",
    "fabulous",
    "fair",
    "faithful",
    "famous",
    "fancy",
    "fantastic",
    "favorable",
    "fearless",
    "fierce",
    "fine",
    "foolish",
    "fragile",
    "frank",
    "frantic",
    "friendly",
    "funny",
    "gentle",
    "gifted",
    "glamorous",
    "gleaming",
    "glittering",
    "glorious",
    "good",
    "gorgeous",
    "graceful",
    "gregarious",
    "grotesque",
    "handsome",
    "happy",
    "healthy",
    "helpful",
    "helpless",
    "hilarious",
    "homely",
    "hungry",
    "hurt",
    "imaginative",
    "important",
    "impossible",
    "incredible",
    "inexpensive",
    "innocent",
    "inquisitive",
    "jealous",
    "jittery",
    "jolly",
    "joyous",
    "kind",
    "lazy",
    "light",
    "lively",
    "long",
    "lovely",
    "lucky",
    "magnificent",
    "mindful",
    "misty",
    "modern",
    "motionless",
    "muddy",
    "mysterious",
    "nervous",
    "nice",
    "obedient",
    "odd",
    "open",
    "optimistic",
    "outrageous",
    "outstanding",
    "perfect",
    "plain",
    "pleasant",
    "poised",
    "powerful",
    "precious",
    "prickly",
    "proud",
    "puzzled",
    "quaint",
    "ravishing",
    "real",
    "relieved",
    "reliable",
    "remarkable",
    "rich",
    "scary",
    "selfish",
    "shiny",
    "shy",
    "sleepy",
    "smiling",
    "sore",
    "sparkling",
    "spectacular",
    "splendid",
    "spotless",
    "stormy",
    "strange",
    "successful",
    "super",
    "talented",
    "tasty",
    "tender",
    "tense",
    "thankful",
    "thoughtful",
    "tired",
    "tough",
    "twinkling",
    "unique",
    "unsightly",
    "unusual",
    "vast",
    "vibrant",
    "victorious",
    "vivacious",
    "wandering",
    "wild",
    "wise",
    "witty",
    "wondrous",
    "worried",
    "wrong",
    "zany",
    "zealous",
];

/// Returns a deterministic pseudo-random human-friendly name for the peer ID.
///
/// The name is generated using a polynomial rolling hash of the base58-encoded
/// peer ID, then selecting an adjective and noun from predefined lists.
pub fn peer_name(id: &PeerId) -> String {
    // p is chosen to be 59 because it's prime and roughly equal to the number of
    // different characters you can have in base58 encoded strings. Base58
    // encoded strings can consist of 58 different alphanumeric characters
    // (123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz)
    const P: u64 = 59;
    const M: u64 = 1_000_000_007; // 1e9 + 7

    let mut hash_value: u64 = 0;
    let mut p_pow: u64 = 1;

    // s is the base58-encoded representation of peer_id
    let s = id.to_base58();

    for c in s.chars() {
        let tmp = (c as u64).wrapping_mul(p_pow);
        hash_value = (hash_value.wrapping_add(tmp)) % M;
        p_pow = (p_pow.wrapping_mul(P)) % M;
    }

    #[allow(clippy::arithmetic_side_effects)]
    let noun_idx = usize::try_from(hash_value.wrapping_rem(
        u64::try_from(NOUNS.len()).expect("NOUNS.len() is always less than u64::MAX"),
    ))
    .expect("hash_value.wrapping_rem(u64::try_from(NOUNS.len())) is always less than usize::MAX");

    #[allow(clippy::arithmetic_side_effects)]
    let adj_idx = usize::try_from(hash_value.wrapping_rem(
        u64::try_from(ADJECTIVES.len()).expect("ADJECTIVES.len() is always less than u64::MAX"),
    ))
    .expect(
        "hash_value.wrapping_rem(u64::try_from(ADJECTIVES.len())) is always less than usize::MAX",
    );

    format!("{}-{}", ADJECTIVES[adj_idx], NOUNS[noun_idx])
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use pluto_eth2util::enr::Record;

    use crate::{name::peer_name, peer::Peer};

    #[test]
    fn test_peer_name_by_enr() {
        let enr_str = "enr:-JG4QBqxg9KCQ1vnvVagJsg08-qbtOjJ9Mkcm3d-FOX1Z2dqdw6Rp0S5lBRC2Uh4_Hk6KvyZoRJY5VGlkVb8scEWXaeGAYDhsvrogmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQMsMU_1-8n0xkoOJD9v-DOSjmc8FFTXv9xWW8gqbZxlcIN0Y3CCPoODdWRwgj6E";

        let enr = Record::try_from(enr_str).unwrap();

        let peer = Peer::from_enr(&enr, 0).unwrap();

        assert_eq!(peer.name, "happy-floor");
    }

    #[test]
    fn test_peer_name_by_peer_id() {
        let peer_id = "16Uiu2HAmDTemdrDfAgG1DX5q3NmfART3PcTFZe69yrNHdde3Qq3v";
        let name = "different-course";

        let p = libp2p::PeerId::from_str(peer_id).unwrap();

        assert_eq!(peer_name(&p), name, "Peer name should be deterministic");
    }
}
