// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

/// dkg.msgKey
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrostMsgKey {
    #[prost(uint32, tag = "1")]
    pub val_idx: u32,
    #[prost(uint32, tag = "2")]
    pub source_id: u32,
    #[prost(uint32, tag = "3")]
    pub target_id: u32,
}
/// Reliable-broadcast
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrostRound1Casts {
    /// One per validator
    #[prost(message, repeated, tag = "1")]
    pub casts: ::prost::alloc::vec::Vec<FrostRound1Cast>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrostRound1Cast {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<FrostMsgKey>,
    #[prost(bytes = "bytes", tag = "2")]
    pub wi: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub ci: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", repeated, tag = "4")]
    pub commitments: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
}
/// Direct peer-to-peer
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrostRound1P2p {
    /// One per validator
    #[prost(message, repeated, tag = "1")]
    pub shares: ::prost::alloc::vec::Vec<FrostRound1ShamirShare>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrostRound1ShamirShare {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<FrostMsgKey>,
    #[prost(uint32, tag = "2")]
    pub id: u32,
    #[prost(bytes = "bytes", tag = "3")]
    pub value: ::prost::bytes::Bytes,
}
/// Reliable-broadcast
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrostRound2Casts {
    /// One per validator
    #[prost(message, repeated, tag = "1")]
    pub casts: ::prost::alloc::vec::Vec<FrostRound2Cast>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrostRound2Cast {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<FrostMsgKey>,
    #[prost(bytes = "bytes", tag = "2")]
    pub verification_key: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub vk_share: ::prost::bytes::Bytes,
}