// This file is @generated by prost-build.
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MsgNodeSig {
    #[prost(bytes = "bytes", tag = "1")]
    pub signature: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "2")]
    pub peer_index: u32,
}