name: Update code coverage

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/coverage.svg"
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings -C debuginfo=0"

jobs:
  coverage:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry and target
        uses: Swatinem/rust-cache@v2

      - name: Install `protobuf`
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: protobuf-compiler
          version: 3.21.12-8.2ubuntu0.2

      - name: Install `oas3-gen`
        run: cargo install oas3-gen@0.24.0

      - name: Install `llvm-tools-preview`
        run: rustup component add llvm-tools-preview

      - name: Install `cargo-llvm-cov`
        run: cargo install cargo-llvm-cov@0.6.24

      - name: Generate coverage report
        run: cargo llvm-cov --locked --workspace --lcov --output-path lcov.info --ignore-filename-regex '^examples/'

      - uses: ImBIOS/lcov-coverage-badge@v1
        with:
          file: lcov.info
