name: Linter check

on:
  push:
    branches: ["main"] # Runs on pushes to main branch
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "flake.nix"
      - "rustfmt.toml"
      - "clippy.toml"
      - ".github/workflows/linter.yml"
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "flake.nix"
      - "rustfmt.toml"
      - "clippy.toml"
      - ".github/workflows/linter.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings -C debuginfo=0"

jobs:
  linter_check:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry and target
        uses: Swatinem/rust-cache@v2

      - name: Install `protobuf`
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: protobuf-compiler
          version: 3.21.12-8.2ubuntu0.2

      - name: Install `oas3-gen`
        run: cargo install oas3-gen@0.24.0

      - name: Install `rustfmt`
        run: rustup +nightly component add rustfmt

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --locked --all-targets --all-features
